### ISSUE TITLE
界面样式问题

### ISSUE THREAD

**Issue by MaoquanTang** [Ahoo-Wang/CoSky#14]
hello，你好，正常运行后用笔记本打开样式会有些问题，dashboard下拉样式问题，configguration-导入、导出超长
另外有没有详细一点的界面功能介绍

**Comment by Ahoo-Wang** [comment]
截个图看一下。

**Comment by MaoquanTang** [comment]
![image](https://user-images.githubusercontent.com/49020903/127945650-7975dda3-8ce5-44e2-b720-5a32a1e22c35.png)

**Comment by MaoquanTang** [comment]
![image](https://user-images.githubusercontent.com/49020903/127945773-9e155ad0-df4b-4c92-90e9-11dcaabd1797.png)

**Comment by Ahoo-Wang** [comment]
请提供一下浏览器版本，以及分辨率

**Comment by MaoquanTang** [comment]
谷歌92.0.4515.107
1920 * 1080

**Comment by Ahoo-Wang** [comment]
https://github.com/Ahoo-Wang/CoSky/releases/tag/1.2.10

**Comment by MaoquanTang** [comment]
好的，谢谢，没别的问题了
