### ISSUE TITLE
如果有安全控制就更好了

### ISSUE THREAD

**Issue by yfm10** [Ahoo-Wang/CoSky#7]
类似的用户名和密码的控制，命名空间权限的控制

**Comment by Ahoo-Wang** [comment]
预计 1.2.0 版本会提供 RBAC 模块。

**Comment by Ahoo-Wang** [comment]
已支持。感谢你的反馈。请参阅：
https://github.com/Ahoo-Wang/CoSky/releases/tag/1.2.0
